package com.nexacare.hospital.enums;

public enum Department {

    GENERAL_MEDICINE,
    CARDIOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    DERMATOLOGY,
    GYNECOLOGY,
    ENT,
    OPHTHALMOLOGY,
    PSYCHIATRY,
    UROLOGY,
    ONCOLOGY,
    GASTROENTEROLOGY,
    PULMONOLOGY,
    ENDOCRINOLOGY,
    NEPHROLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    EMERGENCY_MEDICINE,
    PHYSIOTHERAPY
}